// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsVwlWC65u3ZVbmm4bxvBcMl-arWdKPi8',
    appId: '1:795475133537:web:f4aaf29b6acb855972d620',
    messagingSenderId: '795475133537',
    projectId: 'enchantattire-91816',
    authDomain: 'enchantattire-91816.firebaseapp.com',
    storageBucket: 'enchantattire-91816.appspot.com',
    measurementId: 'G-S73JQ405ES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDuqq_kPNTFFiTpWJKjX76e8AZWJsrNnw',
    appId: '1:795475133537:android:10e1e5693963f11a72d620',
    messagingSenderId: '795475133537',
    projectId: 'enchantattire-91816',
    storageBucket: 'enchantattire-91816.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf-MyKPyLqGyKn0ajaprgcDAg_ROdi2-M',
    appId: '1:795475133537:ios:2761116b00109b6372d620',
    messagingSenderId: '795475133537',
    projectId: 'enchantattire-91816',
    storageBucket: 'enchantattire-91816.appspot.com',
    iosBundleId: 'com.example.enchantAttire',
  );
}
